function [specs, colors, styles] = main_specs()
%MAIN_SPECS The receivers compared in every experiment. Same samples, same supervisor; only weights differ.
specs = [rx_spec("best",   true, "best single dish"), ...
         rx_spec("egc",    true, "equal gain"), ...
         rx_spec("sumple", true, "SUMPLE (blind consensus)"), ...
         rx_spec("sync",   true, "sync-marker only"), ...
         rx_spec("choir",  true, "Choir (verified frames)"), ...
         rx_spec("genie",  true, "bound: knows the data")];
colors = [0.55 0.55 0.55; 0.30 0.60 0.90; 0.90 0.40 0.10; 0.60 0.35 0.75; 0.10 0.65 0.30; 0 0 0];
styles = ["-o", "-s", "-^", "-d", "-o", "--"];
end
